### ISSUE TITLE
Error Attempting fabric.require with Plain JS Object with string field

### ISSUE THREAD

**Issue by chimon2000** [maxkfranz/weaver#14]
When I attempt to pass in a js object to my fabric, I am given the following error:

```
obj["url"] = JSON.parse(""www.test.com"");
                        ^^

SyntaxError: missing ) after argument list
    at process.<anonymous> (.../weaverjs/dist/thread-node-fork.js:61:12)
    at emitTwo (events.js:87:13)
    at process.emit (events.js:172:7)
    at handleMessage (internal/child_process.js:686:10)
    at Pipe.channel.onread (internal/child_process.js:440:11)
undefined:3
```

See code below 

```
  return f.require({url: url}, 'obj').pass(dataToSync).spread(sliceToSync => {

    var obj = _ref_('obj');

    var message = {};
    message.payload = sliceToSync;

    console.log(`syncing to `, obj);

    return JSON.stringify(message);
  }).then(res => {

    console.log('res is ' + res);
    f.stop();
    return res;
  });
```

**Comment by maxkfranz** [comment]
Looks like a quick fix; thanks for the feedback

**Comment by chimon2000** [comment]
Awesome!
